<?php /* Smarty version 2.5.0, created on 2003-04-23 18:09:42
         compiled from footer.tpl */ ?>
<pdffunction:openObject return="all" />
<pdffunction:saveState />
<pdffunction:setStrokeColor arg="0" arg="0" arg="0" arg="1" />
<pdffunction:line arg="20" arg="40" arg="578" arg="40" />
<pdffunction:line arg="20" arg="822" arg="578" arg="822" />
<pdffunction:addText arg="50" arg="34" arg="6" arg="Generated by phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
 http://www.phpdoc.org - http://www.sourceforge.net/projects/phpdocu" />
<pdffunction:restoreState />
<pdffunction:closeObject />

<pdffunction:addObject arg=$all arg="all" />