<?php /* Smarty version 2.5.0, created on 2003-04-23 16:13:30
         compiled from index.tpl */ ?>
<?php echo '<?xml'; ?>
 version="1.0" encoding="iso-8859-1"<?php echo '?>'; ?>

<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//FR"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
   <html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<!-- Generated by phpDocumentor on <?php echo $this->_tpl_vars['date']; ?>
  -->
  <title><?php echo $this->_tpl_vars['title']; ?>
</title>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>

<FRAMESET cols='220,*'>
	<FRAMESET rows='220,*'>
		<FRAME src='packages.html' name='left_top'>
		<FRAME src='<?php echo $this->_tpl_vars['start']; ?>
' name='left_bottom'>
	</FRAMESET>
	<FRAME src='<?php echo $this->_tpl_vars['blank']; ?>
.html' name='right'>
	<NOFRAMES>
		<H2>Frame Alert</H2>
		<P>This document is designed to be viewed using the frames feature.
		If you see this message, you are using a non-frame-capable web client.</P>
	</NOFRAMES>
</FRAMESET>
</HTML>