<?php

if (function_exists ('curl_init')) {
	return;
}

$GLOBALS['_curl_options'] = array ();
$GLOBALS['_curl_error'] = null;
$GLOBALS['_curl_errno'] = null;

define ('CURLOPT_BINARYTRANSFER', 'CURLOPT_BINARYTRANSFER');
define ('CURLOPT_CRLF', 'CURLOPT_CRLF');
define ('CURLOPT_DNS_USE_GLOBAL_CACHE', 'CURLOPT_DNS_USE_GLOBAL_CACHE');
define ('CURLOPT_FAILONERROR', 'CURLOPT_FAILONERROR');
define ('CURLOPT_FILETIME', 'CURLOPT_FILETIME');
define ('CURLOPT_FOLLOWLOCATION', 'CURLOPT_FOLLOWLOCATION');
define ('CURLOPT_FORBID_REUSE', 'CURLOPT_FORBID_REUSE');
define ('CURLOPT_FRESH_CONNECT', 'CURLOPT_FRESH_CONNECT');
define ('CURLOPT_FTP_USE_EPRT', 'CURLOPT_FTP_USE_EPRT');
define ('CURLOPT_FTP_USE_EPSV', 'CURLOPT_FTP_USE_EPSV');
define ('CURLOPT_FTPAPPEND', 'CURLOPT_FTPAPPEND');
define ('CURLOPT_FTPASCII', 'CURLOPT_FTPASCII');
define ('CURLOPT_FTPLISTONLY', 'CURLOPT_FTPLISTONLY');
define ('CURLOPT_HEADER', 'CURLOPT_HEADER');
define ('CURLOPT_HTTPGET', 'CURLOPT_HTTPGET');
define ('CURLOPT_HTTPPROXYTUNNEL', 'CURLOPT_HTTPPROXYTUNNEL');
define ('CURLOPT_MUTE', 'CURLOPT_MUTE');
define ('CURLOPT_NETRC', 'CURLOPT_NETRC');
define ('CURLOPT_NOBODY', 'CURLOPT_NOBODY');
define ('CURLOPT_NOPROGRESS', 'CURLOPT_NOPROGRESS');
define ('CURLOPT_NOSIGNAL', 'CURLOPT_NOSIGNAL');
define ('CURLOPT_POST', 'CURLOPT_POST');
define ('CURLOPT_PUT', 'CURLOPT_PUT');
define ('CURLOPT_RETURNTRANSFER', 'CURLOPT_RETURNTRANSFER');
define ('CURLOPT_SSL_VERIFYPEER', 'CURLOPT_SSL_VERIFYPEER');
define ('CURLOPT_TRANSFERTEXT', 'CURLOPT_TRANSFERTEXT');
define ('CURLOPT_UNRESTRICTED_AUTH', 'CURLOPT_UNRESTRICTED_AUTH');
define ('CURLOPT_UPLOAD', 'CURLOPT_UPLOAD');
define ('CURLOPT_VERBOSE', 'CURLOPT_VERBOSE');
define ('CURLOPT_BUFFERSIZE', 'CURLOPT_BUFFERSIZE');
define ('CURLOPT_CLOSEPOLICY', 'CURLOPT_CLOSEPOLICY');
define ('CURLOPT_CONNECTTIMEOUT', 'CURLOPT_CONNECTTIMEOUT');
define ('CURLOPT_DNS_CACHE_TIMEOUT', 'CURLOPT_DNS_CACHE_TIMEOUT');
define ('CURLOPT_FTPSSLAUTH', 'CURLOPT_FTPSSLAUTH');
define ('CURLOPT_HTTP_VERSION', 'CURLOPT_HTTP_VERSION');
define ('CURLOPT_HTTPAUTH	', 'CURLOPT_HTTPAUTH	');
define ('CURLOPT_INFILESIZE', 'CURLOPT_INFILESIZE');
define ('CURLOPT_LOW_SPEED_LIMIT', 'CURLOPT_LOW_SPEED_LIMIT');
define ('CURLOPT_LOW_SPEED_TIME', 'CURLOPT_LOW_SPEED_TIME');
define ('CURLOPT_MAXCONNECTS', 'CURLOPT_MAXCONNECTS');
define ('CURLOPT_MAXREDIRS', 'CURLOPT_MAXREDIRS');
define ('CURLOPT_PORT', 'CURLOPT_PORT');
define ('CURLOPT_PROXYAUTH', 'CURLOPT_PROXYAUTH');
define ('CURLOPT_PROXYPORT', 'CURLOPT_PROXYPORT');
define ('CURLOPT_PROXYTYPE', 'CURLOPT_PROXYTYPE');
define ('CURLOPT_RESUME_FROM', 'CURLOPT_RESUME_FROM');
define ('CURLOPT_SSL_VERIFYHOST', 'CURLOPT_SSL_VERIFYHOST');
define ('CURLOPT_SSLVERSION', 'CURLOPT_SSLVERSION');
define ('CURLOPT_TIMECONDITION', 'CURLOPT_TIMECONDITION');
define ('CURLOPT_TIMEOUT', 'CURLOPT_TIMEOUT');
define ('CURLOPT_TIMEVALUE', 'CURLOPT_TIMEVALUE');
define ('CURLOPT_CAINFO', 'CURLOPT_CAINFO');
define ('CURLOPT_CAPATH', 'CURLOPT_CAPATH');
define ('CURLOPT_COOKIE', 'CURLOPT_COOKIE');
define ('CURLOPT_COOKIEFILE', 'CURLOPT_COOKIEFILE');
define ('CURLOPT_COOKIEJAR', 'CURLOPT_COOKIEJAR');
define ('CURLOPT_CUSTOMREQUEST', 'CURLOPT_CUSTOMREQUEST');
define ('CURLOPT_EGBSOCKET', 'CURLOPT_EGBSOCKET');
define ('CURLOPT_ENCODING', 'CURLOPT_ENCODING');
define ('CURLOPT_FTPPORT', 'CURLOPT_FTPPORT');
define ('CURLOPT_INTERFACE', 'CURLOPT_INTERFACE');
define ('CURLOPT_KRB4LEVEL', 'CURLOPT_KRB4LEVEL');
define ('CURLOPT_POSTFIELDS', 'CURLOPT_POSTFIELDS');
define ('CURLOPT_PROXY', 'CURLOPT_PROXY');
define ('CURLOPT_PROXYUSERPWD', 'CURLOPT_PROXYUSERPWD');
define ('CURLOPT_RANDOM_FILE', 'CURLOPT_RANDOM_FILE');
define ('CURLOPT_RANGE', 'CURLOPT_RANGE');
define ('CURLOPT_REFERER', 'CURLOPT_REFERER');
define ('CURLOPT_SSL_CIPHER_LIST', 'CURLOPT_SSL_CIPHER_LIST');
define ('CURLOPT_SSLCERT', 'CURLOPT_SSLCERT');
define ('CURLOPT_SSLCERTPASSWD', 'CURLOPT_SSLCERTPASSWD');
define ('CURLOPT_SSLCERTTYPE', 'CURLOPT_SSLCERTTYPE');
define ('CURLOPT_SSLENGINE', 'CURLOPT_SSLENGINE');
define ('CURLOPT_SSLENGINE_DEFAULT', 'CURLOPT_SSLENGINE_DEFAULT');
define ('CURLOPT_SSLKEY', 'CURLOPT_SSLKEY');
define ('CURLOPT_SSLKEYPASSWD', 'CURLOPT_SSLKEYPASSWD');
define ('CURLOPT_SSLKEYTYPE', 'CURLOPT_SSLKEYTYPE');
define ('CURLOPT_URL', 'CURLOPT_URL');
define ('CURLOPT_USERAGENT', 'CURLOPT_USERAGENT');
define ('CURLOPT_USERPWD', 'CURLOPT_USERPWD');
define ('CURLOPT_HTTP200ALIASES', 'CURLOPT_HTTP200ALIASES');
define ('CURLOPT_HTTPHEADER', 'CURLOPT_HTTPHEADER');
define ('CURLOPT_POSTQUOTE', 'CURLOPT_POSTQUOTE');
define ('CURLOPT_QUOTE', 'CURLOPT_QUOTE');
define ('CURLOPT_FILE', 'CURLOPT_FILE');
define ('CURLOPT_INFILE', 'CURLOPT_INFILE');
define ('CURLOPT_STDERR', 'CURLOPT_STDERR');
define ('CURLOPT_WRITEHEADER', 'CURLOPT_WRITEHEADER');
define ('CURLOPT_HEADERFUNCTION', 'CURLOPT_HEADERFUNCTION');
define ('CURLOPT_PASSWDFUNCTION', 'CURLOPT_PASSWDFUNCTION');
define ('CURLOPT_READFUNCTION', 'CURLOPT_READFUNCTION');
define ('CURLOPT_WRITEFUNCTION', 'CURLOPT_WRITEFUNCTION');

function curl_init () {
	if (! is_file ('/usr/bin/curl')) {
		return false;
	}
	return true;
}

function curl_setopt ($ch, $key, $value) {
	$GLOBALS['_curl_options'][$key] = $value;
	return true;
}

function curl_exec ($ch) {
	// get $data and $script from _curl_options
	global $_curl_options;
	$data = $_curl_options[CURLOPT_POSTFIELDS];
	$script = $_curl_options[CURLOPT_URL];

	exec ('/usr/bin/curl -d ' . escapeshellarg ($data) . ' ' . escapeshellarg ($script), $res);

	$str = join ('', $res);
	$res = array ();
	$res = explode ('|', $str);
	$responseCode = $res[2];
	if ($responseCode == 1) {
		return $str;
	} else {
		if ($res[3]) {
			$GLOBALS['_curl_error'] = $res[3];
		} else {
			$GLOBALS['_curl_error'] = $str;
		}
		$GLOBALS['_curl_errno'] = $responseCode;
		return false;
	}
}

function curl_error ($ch) {
	return $GLOBALS['_curl_error'];
}

function curl_errno ($ch) {
	return $GLOBALS['_curl_errno'];
}

function curl_close ($ch) {
	return true;
}

?>