<?php /* Smarty version 2.5.0, created on 2003-04-23 22:06:08
         compiled from header.tpl */ ?>
<!--
	IE 6 makes the page to wide with the following doctype. I accept
	standards if they help me, not if they make anything even harder!
//-->
<!--<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN' 'http://www.w3.org/TR/REC-html40/loose.dtd'>//-->
<!--NewPage-->
<HTML>
<HEAD>
	<!-- Generated by PhpDoc date: '<?php echo $this->_tpl_vars['date']; ?>
' -->
	<TITLE><?php echo $this->_tpl_vars['title']; ?>
</TITLE>
<LINK REL ='stylesheet' TYPE='text/css' HREF='<?php echo $this->_tpl_vars['subdir']; ?>
media/stylesheet.css' TITLE='Style'>
<?php if ($this->_tpl_vars['bgleft']): ?>
<STYLE type="text/css"><!--
	BODY								{
											background-image		: url("<?php echo $this->_tpl_vars['subdir']; ?>
media/bg_left.png");
											background-repeat		: repeat-y;
										}
//--></STYLE>
<?php endif; ?>
</HEAD>
<BODY <?php if (! $this->_tpl_vars['bgleft']): ?>BGCOLOR='white'<?php endif; ?>>
<a name="top"><!-- --></a>