<?php /* Smarty version 2.5.0, created on 2003-05-26 01:15:44
         compiled from tutorial.tpl */ ?>
<?php echo $this->_tpl_vars['contents']; ?>

<!-- Generated by phpDocumentor v <?php echo $this->_tpl_vars['phpdocversion']; ?>
 <?php echo $this->_tpl_vars['phpdocwebsite']; ?>
 -->
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
sgml-parent-document:nil
sgml-default-dtd-file:"../../../../manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->