insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 1, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 2, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 3, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "", "", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 4, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 5, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 6, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 7, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 8, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 9, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 10, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 11, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 12, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 13, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 14, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 15, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 16, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 17, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "jd@localhost", "jon", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 18, 1);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 19, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 20, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 21, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "", "", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 22, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 23, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 24, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 25, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 26, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 27, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 28, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 29, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 30, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 31, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 32, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 33, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 34, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 35, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 36, 2);
insert into sitemailer2_recipient (id, email, firstname, lastname, organization, website, created) values (null, "ian@localhost", "ian", "dart", "", "", "");
insert into sitemailer2_recipient_belongs_to_category (id, recipient, category) values (null, 37, 2);

